#ifndef GUARD_CONSTANTS_EM_MAPS_H
#define GUARD_CONSTANTS_EM_MAPS_H

// ======= //
// MAP IDS //
// ======= //
// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY (0x7F | 0x7F)
#define MAP_FORTREE_CITY (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY (0x7F | 0x7F)
#define MAP_LITTLEROOT_TOWN (0x7F | 0x7F)
#define MAP_OLDALE_TOWN (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN (0x7F | 0x7F)
#define MAP_ROUTE101 (0x7F | 0x7F)
#define MAP_ROUTE102 (0x7F | 0x7F)
#define MAP_ROUTE103 (0x7F | 0x7F)
#define MAP_ROUTE104 (0x7F | 0x7F)
#define MAP_ROUTE105 (0x7F | 0x7F)
#define MAP_ROUTE106 (0x7F | 0x7F)
#define MAP_ROUTE107 (0x7F | 0x7F)
#define MAP_ROUTE108 (0x7F | 0x7F)
#define MAP_ROUTE109 (0x7F | 0x7F)
#define MAP_ROUTE110 (0x7F | 0x7F)
#define MAP_ROUTE111 (0x7F | 0x7F)
#define MAP_ROUTE112 (0x7F | 0x7F)
#define MAP_ROUTE113 (0x7F | 0x7F)
#define MAP_ROUTE114 (0x7F | 0x7F)
#define MAP_ROUTE115 (0x7F | 0x7F)
#define MAP_ROUTE116 (0x7F | 0x7F)
#define MAP_ROUTE117 (0x7F | 0x7F)
#define MAP_ROUTE118 (0x7F | 0x7F)
#define MAP_ROUTE119 (0x7F | 0x7F)
#define MAP_ROUTE120 (0x7F | 0x7F)
#define MAP_ROUTE121 (0x7F | 0x7F)
#define MAP_ROUTE122 (0x7F | 0x7F)
#define MAP_ROUTE123 (0x7F | 0x7F)
#define MAP_ROUTE124 (0x7F | 0x7F)
#define MAP_ROUTE125 (0x7F | 0x7F)
#define MAP_ROUTE126 (0x7F | 0x7F)
#define MAP_ROUTE127 (0x7F | 0x7F)
#define MAP_ROUTE128 (0x7F | 0x7F)
#define MAP_ROUTE129 (0x7F | 0x7F)
#define MAP_ROUTE130 (0x7F | 0x7F)
#define MAP_ROUTE131 (0x7F | 0x7F)
#define MAP_ROUTE132 (0x7F | 0x7F)
#define MAP_ROUTE133 (0x7F | 0x7F)
#define MAP_ROUTE134 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE124 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE126 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE127 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE128 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE129 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE105 (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE125 (0x7F | 0x7F)
 
// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F (0x7F | 0x7F)
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F (0x7F | 0x7F)
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F (0x7F | 0x7F)
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F (0x7F | 0x7F)
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (0x7F | 0x7F)
 
// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1 (0x7F | 0x7F)
#define MAP_OLDALE_TOWN_HOUSE2 (0x7F | 0x7F)
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_OLDALE_TOWN_MART (0x7F | 0x7F)
 
// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1 (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN_GYM (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN_HALL (0x7F | 0x7F)
#define MAP_DEWFORD_TOWN_HOUSE2 (0x7F | 0x7F)
 
// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_GYM_1F (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_GYM_B1F (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_HOUSE (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_MART (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
 
// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE (0x7F | 0x7F)
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_MART (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (0x7F | 0x7F)
#define MAP_VERDANTURF_TOWN_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_HOUSE1 (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_HOUSE2 (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_HOUSE3 (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_HOUSE4 (0x7F | 0x7F)
#define MAP_PACIFIDLOG_TOWN_HOUSE5 (0x7F | 0x7F)
 
// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_GYM (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_PETALBURG_CITY_MART (0x7F | 0x7F)
 
// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_HARBOR (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_HOUSE (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_SLATEPORT_CITY_MART (0x7F | 0x7F)
 
// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_GYM (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_BIKE_SHOP (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_GAME_CORNER (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_MAUVILLE_CITY_MART (0x7F | 0x7F)
 
// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_GYM (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_MART (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_FLAT1_1F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_FLAT1_2F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_FLAT2_1F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_FLAT2_2F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_FLAT2_3F (0x7F | 0x7F)
#define MAP_RUSTBORO_CITY_HOUSE3 (0x7F | 0x7F)
 
// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_FORTREE_CITY_GYM (0x7F | 0x7F)
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_FORTREE_CITY_MART (0x7F | 0x7F)
#define MAP_FORTREE_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_FORTREE_CITY_HOUSE3 (0x7F | 0x7F)
#define MAP_FORTREE_CITY_HOUSE4 (0x7F | 0x7F)
#define MAP_FORTREE_CITY_HOUSE5 (0x7F | 0x7F)
#define MAP_FORTREE_CITY_DECORATION_SHOP (0x7F | 0x7F)
 
// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_CONTEST_HALL (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_UNUSED_MART (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_HARBOR (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_HOUSE3 (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_HOUSE4 (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP (0x7F | 0x7F)
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (0x7F | 0x7F)
 
// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_GYM (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_MART (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_HOUSE3 (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_HOUSE4 (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F (0x7F | 0x7F)
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F (0x7F | 0x7F)
 
// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_GYM_1F (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_GYM_B1F (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_MART (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE1 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE2 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE3 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE4 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE5 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE6 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_HOUSE7 (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F (0x7F | 0x7F)
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (0x7F | 0x7F)
 
// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL1 (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL2 (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL3 (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL4 (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL5 (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE (0x7F | 0x7F)
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0x7F | 0x7F)
#define MAP_ROUTE111_OLD_LADYS_REST_STOP (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION (0x7F | 0x7F)
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE (0x7F | 0x7F)
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (0x7F | 0x7F)
#define MAP_ROUTE114_LANETTES_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0x7F | 0x7F)
 
// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R (0x7F | 0x7F)
#define MAP_METEOR_FALLS_1F_2R (0x7F | 0x7F)
#define MAP_METEOR_FALLS_B1F_1R (0x7F | 0x7F)
#define MAP_METEOR_FALLS_B1F_2R (0x7F | 0x7F)
#define MAP_RUSTURF_TUNNEL (0x7F | 0x7F)
#define MAP_UNDERWATER_SOOTOPOLIS_CITY (0x7F | 0x7F)
#define MAP_DESERT_RUINS (0x7F | 0x7F)
#define MAP_GRANITE_CAVE_1F (0x7F | 0x7F)
#define MAP_GRANITE_CAVE_B1F (0x7F | 0x7F)
#define MAP_GRANITE_CAVE_B2F (0x7F | 0x7F)
#define MAP_GRANITE_CAVE_STEVENS_ROOM (0x7F | 0x7F)
#define MAP_PETALBURG_WOODS (0x7F | 0x7F)
#define MAP_MT_CHIMNEY (0x7F | 0x7F)
#define MAP_JAGGED_PASS (0x7F | 0x7F)
#define MAP_FIERY_PATH (0x7F | 0x7F)
#define MAP_MT_PYRE_1F (0x7F | 0x7F)
#define MAP_MT_PYRE_2F (0x7F | 0x7F)
#define MAP_MT_PYRE_3F (0x7F | 0x7F)
#define MAP_MT_PYRE_4F (0x7F | 0x7F)
#define MAP_MT_PYRE_5F (0x7F | 0x7F)
#define MAP_MT_PYRE_6F (0x7F | 0x7F)
#define MAP_MT_PYRE_EXTERIOR (0x7F | 0x7F)
#define MAP_MT_PYRE_SUMMIT (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_1F (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_B1F (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_B2F (0x7F | 0x7F)
#define MAP_UNDERWATER_SEAFLOOR_CAVERN (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ENTRANCE (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM1 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM2 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM3 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM4 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM5 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM6 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM7 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM8 (0x7F | 0x7F)
#define MAP_SEAFLOOR_CAVERN_ROOM9 (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_ENTRANCE (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_1F (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (0x7F | 0x7F)
#define MAP_CAVE_OF_ORIGIN_B1F (0x7F | 0x7F)
 
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM (0x7F | 0x7F)
#define MAP_NEW_MAUVILLE_ENTRANCE (0x7F | 0x7F)
#define MAP_NEW_MAUVILLE_INSIDE (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_DECK (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_CORRIDORS_1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_ROOMS_1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_ROOMS_B1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_ROOMS2_B1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_UNDERWATER1 (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_ROOM_B1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_ROOMS2_1F (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_UNDERWATER2 (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS (0x7F | 0x7F)
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS (0x7F | 0x7F)
#define MAP_ISLAND_CAVE (0x7F | 0x7F)
#define MAP_ANCIENT_TOMB (0x7F | 0x7F)
#define MAP_UNDERWATER_ROUTE134 (0x7F | 0x7F)
#define MAP_UNDERWATER_SEALED_CHAMBER (0x7F | 0x7F)
#define MAP_SEALED_CHAMBER_OUTER_ROOM (0x7F | 0x7F)
#define MAP_SEALED_CHAMBER_INNER_ROOM (0x7F | 0x7F)
#define MAP_SCORCHED_SLAB (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1 (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2 (0x7F | 0x7F)
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3 (0x7F | 0x7F)
#define MAP_SKY_PILLAR_ENTRANCE (0x7F | 0x7F)
#define MAP_SKY_PILLAR_OUTSIDE (0x7F | 0x7F)
#define MAP_SKY_PILLAR_1F (0x7F | 0x7F)
#define MAP_SKY_PILLAR_2F (0x7F | 0x7F)
#define MAP_SKY_PILLAR_3F (0x7F | 0x7F)
#define MAP_SKY_PILLAR_4F (0x7F | 0x7F)
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM (0x7F | 0x7F)
#define MAP_SKY_PILLAR_5F (0x7F | 0x7F)
#define MAP_SKY_PILLAR_TOP (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_1F (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_2F_1R (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_2F_2R (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_3F_1R (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_3F_2R (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_4F (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_3F_3R (0x7F | 0x7F)
#define MAP_MAGMA_HIDEOUT_2F_3R (0x7F | 0x7F)
#define MAP_MIRAGE_TOWER_1F (0x7F | 0x7F)
#define MAP_MIRAGE_TOWER_2F (0x7F | 0x7F)
#define MAP_MIRAGE_TOWER_3F (0x7F | 0x7F)
#define MAP_MIRAGE_TOWER_4F (0x7F | 0x7F)
#define MAP_DESERT_UNDERPASS (0x7F | 0x7F)
#define MAP_ARTISAN_CAVE_B1F (0x7F | 0x7F)
#define MAP_ARTISAN_CAVE_1F (0x7F | 0x7F)
#define MAP_UNDERWATER_MARINE_CAVE (0x7F | 0x7F)
#define MAP_MARINE_CAVE_ENTRANCE (0x7F | 0x7F)
#define MAP_MARINE_CAVE_END (0x7F | 0x7F)
#define MAP_TERRA_CAVE_ENTRANCE (0x7F | 0x7F)
#define MAP_TERRA_CAVE_END (0x7F | 0x7F)
#define MAP_ALTERING_CAVE (0x7F | 0x7F)
#define MAP_METEOR_FALLS_STEVENS_CAVE (0x7F | 0x7F)
 
// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BROWN_CAVE1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BLUE_CAVE1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_YELLOW_CAVE1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_TREE1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_SHRUB1 (0x7F | 0x7F)
#define MAP_SECRET_BASE_RED_CAVE2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BROWN_CAVE2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BLUE_CAVE2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_YELLOW_CAVE2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_TREE2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_SHRUB2 (0x7F | 0x7F)
#define MAP_SECRET_BASE_RED_CAVE3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BROWN_CAVE3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BLUE_CAVE3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_YELLOW_CAVE3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_TREE3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_SHRUB3 (0x7F | 0x7F)
#define MAP_SECRET_BASE_RED_CAVE4 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BROWN_CAVE4 (0x7F | 0x7F)
#define MAP_SECRET_BASE_BLUE_CAVE4 (0x7F | 0x7F)
#define MAP_SECRET_BASE_YELLOW_CAVE4 (0x7F | 0x7F)
#define MAP_SECRET_BASE_TREE4 (0x7F | 0x7F)
#define MAP_SECRET_BASE_SHRUB4 (0x7F | 0x7F)
 
#define MAP_CONTEST_HALL (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL1 (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL2 (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL3 (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL4 (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL5 (0x7F | 0x7F)
#define MAP_UNUSED_CONTEST_HALL6 (0x7F | 0x7F)
#define MAP_CONTEST_HALL_BEAUTY (0x7F | 0x7F)
#define MAP_CONTEST_HALL_TOUGH (0x7F | 0x7F)
#define MAP_CONTEST_HALL_COOL (0x7F | 0x7F)
#define MAP_CONTEST_HALL_SMART (0x7F | 0x7F)
#define MAP_CONTEST_HALL_CUTE (0x7F | 0x7F)
#define MAP_INSIDE_OF_TRUCK (0x7F | 0x7F)
#define MAP_SS_TIDAL_CORRIDOR (0x7F | 0x7F)
#define MAP_SS_TIDAL_LOWER_DECK (0x7F | 0x7F)
#define MAP_SS_TIDAL_ROOMS (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE01 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE02 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE03 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE04 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE05 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE06 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE07 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE08 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE09 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE10 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE11 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE12 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE13 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE14 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE15 (0x7F | 0x7F)
#define MAP_BATTLE_PYRAMID_SQUARE16 (0x7F | 0x7F)
 
// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_SOUTHERN_ISLAND_EXTERIOR (0x7F | 0x7F)
#define MAP_SOUTHERN_ISLAND_INTERIOR (0x7F | 0x7F)
#define MAP_SAFARI_ZONE_REST_HOUSE (0x7F | 0x7F)
#define MAP_SAFARI_ZONE_NORTHEAST (0x7F | 0x7F)
#define MAP_SAFARI_ZONE_SOUTHEAST (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_RANKING_HALL (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE1 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE2 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE3 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE4 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE5 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE6 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE7 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE8 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_LOUNGE9 (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F (0x7F | 0x7F)
#define MAP_BATTLE_FRONTIER_MART (0x7F | 0x7F)
#define MAP_FARAWAY_ISLAND_ENTRANCE (0x7F | 0x7F)
#define MAP_FARAWAY_ISLAND_INTERIOR (0x7F | 0x7F)
 
#define MAP_TRAINER_HILL_ENTRANCE (0x7F | 0x7F)
#define MAP_TRAINER_HILL_1F (0x7F | 0x7F)
#define MAP_TRAINER_HILL_2F (0x7F | 0x7F)
#define MAP_TRAINER_HILL_3F (0x7F | 0x7F)
#define MAP_TRAINER_HILL_4F (0x7F | 0x7F)
#define MAP_TRAINER_HILL_ELEVATOR (0x7F | 0x7F)
#define MAP_TRAINER_HILL_ROOF (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE (0x7F | 0x7F)
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_END (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7 (0x7F | 0x7F)
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8 (0x7F | 0x7F)
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (0x7F | 0x7F)
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0x7F | 0x7F)
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (0x7F | 0x7F)
#define MAP_ROUTE119_HOUSE (0x7F | 0x7F)
 
// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0x7F | 0x7F)


#define MAP_VICTORY_ROAD_B2F (0x7F | 0x7F)


// ======= //
// LAYOUTS //
// ======= //
#define LAYOUT_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_OUTSIDE_WEST 0xFF
#define LAYOUT_BATTLE_ELEVATOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_DOME_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_OUTSIDE_EAST 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_UNUSED 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE01 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE02 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE03 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE04 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE05 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE06 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE07 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE08 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE09 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE10 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE11 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE12 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE13 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE14 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE15 0xFF
#define LAYOUT_BATTLE_PYRAMID_SQUARE16 0xFF
#define LAYOUT_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP 0xFF
#define LAYOUT_BATTLE_TENT_LOBBY 0xFF
#define LAYOUT_BATTLE_TENT_CORRIDOR 0xFF
#define LAYOUT_BATTLE_TENT_BATTLE_ROOM 0xFF

#define LAYOUT_TRAINER_HILL_ENTRANCE 0xFF
#define LAYOUT_TRAINER_HILL_1F 0xFF
#define LAYOUT_TRAINER_HILL_2F 0xFF
#define LAYOUT_TRAINER_HILL_3F 0xFF
#define LAYOUT_TRAINER_HILL_4F 0xFF
#define LAYOUT_TRAINER_HILL_ROOF 0xFF

#endif // GUARD_CONSTANTS_EM_MAPS_H
